services:
  postgres:
    image: postgres:latest
    container_name: veterinerapp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: veterinerapp
    volumes:
      - postgres_data:/var/lib/postgresql/db

volumes:
  postgres_data: